services:
  db:
    image: ghcr.io/dbsystel/postgresql-partman:17
    restart: always
    environment:
      - POSTGRES_DB=happy-chat-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - happy-chat-db-data:/var/lib/postgresql/data
      - ./init-pg-partman.sql:/docker-entrypoint-initdb.d/init-pg-partman.sql

volumes:
  happy-chat-db-data:
